name: build

on:
  push:
    branches:
      - source
  repository_dispatch:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull rocstreaming/env-sphinx

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build documentation
        run: |
          git clone https://github.com/roc-streaming/roc-toolkit.git
          scripts/ci_checks/docker.sh env-sphinx scons -C roc-toolkit --enable-sphinx --enable-doxygen docs
          cp -av roc-toolkit/docs/html www/toolkit

      - name: Publish web-site
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: content
          folder: www
          single-commit: true
