name: build

on:
  push:
    branches:
      - source
  repository_dispatch:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/roc-toolkit.git
          path: roc-toolkit

      - name: Pull docker image
        run: docker pull rocstreaming/env-sphinx

      - name: Build documentation
        run: |
          docker run --rm -t -u "${UID}" -v "$(pwd)":/opt/roc -w /opt/roc env-sphinx scons -C roc-toolkit --enable-sphinx --enable-doxygen docs
          cp -av roc-toolkit/docs/html www/toolkit

      - name: Publish web-site
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: content
          folder: www
          single-commit: true
